git_repos = [
]

[pre_commands]

[commands]
"NPM" = "npm update -g"
"brew cask" = "brew cask upgrade"
"pip" = "pip list -o --format freeze | cut -d '=' -f 1 | xargs pip install -U --upgrade-strategy eager"